package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallShoporderGoods;
import org.linlinjava.litemall.db.domain.LitemallShoporderGoodsExample;

public interface LitemallShoporderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     */
    long countByExample(LitemallShoporderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallShoporderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     */
    int insert(LitemallShoporderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     */
    int insertSelective(LitemallShoporderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallShoporderGoods selectOneByExample(LitemallShoporderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallShoporderGoods selectOneByExampleSelective(@Param("example") LitemallShoporderGoodsExample example, @Param("selective") LitemallShoporderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallShoporderGoods> selectByExampleSelective(@Param("example") LitemallShoporderGoodsExample example, @Param("selective") LitemallShoporderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     */
    List<LitemallShoporderGoods> selectByExample(LitemallShoporderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallShoporderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallShoporderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     */
    LitemallShoporderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallShoporderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallShoporderGoods record, @Param("example") LitemallShoporderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallShoporderGoods record, @Param("example") LitemallShoporderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallShoporderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallShoporderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallShoporderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shoporder_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}