package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallShop;
import org.linlinjava.litemall.db.domain.LitemallShopExample;

public interface LitemallShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     */
    long countByExample(LitemallShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     */
    int insert(LitemallShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     */
    int insertSelective(LitemallShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallShop selectOneByExample(LitemallShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallShop selectOneByExampleSelective(@Param("example") LitemallShopExample example, @Param("selective") LitemallShop.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallShop> selectByExampleSelective(@Param("example") LitemallShopExample example, @Param("selective") LitemallShop.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     */
    List<LitemallShop> selectByExample(LitemallShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallShop selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallShop.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     */
    LitemallShop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallShop record, @Param("example") LitemallShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallShop record, @Param("example") LitemallShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallShop record);
}